ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introduction and Goals

WIQ! es un proyecto desarrollado para la asignatura "Arquitectura de Software" del grado de Ingeniería Informática de la Escuela de Ingeniería Informática de la Universidad de Oviedo. Este proyecto toma como base el proyecto wiq, puesto a la disposición de los alumnos por los profesores de la asignatura.
WIQ! ha sido encargado a la empresa HappySw por RTVE, con el objetivo de recrear su famoso concurso Saber y ganar en una versión web accesible para todo el mundo. Este proyecto será realizado por el equipo de desarrollo es1a formado por:

* Martín Cancio Barrera, mailto:UO287561@uniovi.es[_UO287561_].

* Iyán Fernández Riol, mailto:UO288231@uniovi.es[_UO288231_].

* Rodrigo García Iglesias, mailto:UO276396@uniovi.es[_UO276396_].

* Alfredo Jirout Cid, mailto:UO288443@uniovi.es[_UO288443_]. 

WIQ! es un software mediante el cual los usuarios pueden emular ser los participantes del concurso Saber y ganar, que cuenta con numerosas funcionalidades:

* Jugar a varios de los modos de juego vistos en el programa

* Registrarse para poder llevar registro de sus estadísticas en el juego

* Jugar con amigos

* Ajustar las temáticas de las preguntas, el tiempo de respuesta, el número de preguntas...
***

=== Requirements Overview

* El sistema contará al menos con un frontend web que estará desplegado y el acceso será a través de la Web.
* Los usuarios podrán registrarse en el sistema y consultar el histórico de su participación en el sistema: número de juegos, preguntas acertadas/falladas, tiempos, etc.
* Las preguntas serán generadas automáticamente a partir de los datos de Wikidata.
* Las preguntas deberán responderse en un plazo de tiempo determinado.
* Cada pregunta tendrá una respuesta correcta y varias respuestas incorrectas o distractoras. Tanto la respuesta correcta como las incorrectas se generarán automáticamente.
* El sistema permitirá acceder a la información de los usuarios a través de un API.
* El sistema permitirá acceder a la información de las preguntas generadas a través de un API.


=== Quality Goals


[options="header"]
|===
| Priority | Quality Goal | Motivation

| *1*
| *_Usabilidad_*
| La aplicación debe ser intuitiva para los usuarios, facilitándoles la interacción con la misma independientemente de sus habilidades.

| *2*
| *_Mantenibilidad_*
| La aplicación debe contar con un diseño bien definido y estructurado, de tal forma que sea sencillo realizar modificaciones y/o ampliaciones.

| *3*
| *_Privacidad_*
| La aplicación debe garantizar la privacidad de la información de sus usuarios, contando con mecanismos para evitar intrusiones en el sistema.
|===

=== Stakeholders

[options="header"]
|===
|Role/Name|Contact|Expectations 

| *_Estudiantes (HappySw)_*
| Martín Cancio Barrera, Iyán Fernández Riol, Rodrigo García Iglesias y Alfredo Jirout Cid
| Los estudiantes son los desarrolladores de la aplicación. Están a cargo del desarrollo completo, lo que mejorará sus habilidades tanto de programación como de trabajo en grupo.

| *_Usuarios_*
| Cualquier persona que utilice la aplicación
| Los usuarios son los que en última instancia van a utilizar la aplicación, por lo que debe ser intuitiva y fácil de entender.

| *_Profesores_*
| José Emilio Labra Gayo, Pablo González González, Jorge Álvarez Fidalgo y Cristian Augusto Alonso
| Son los supervisores del proyecto, y ayudarán a los estudiantes para asegurarse de que el proyecto llegue a buen puerto.

| *_RTVE_*
| RTVE
| Son los principales interesados en la aplicación, puesto que son los que la han encargado, para que sus espectadores puedan utilizarla.
|===
