ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

We developed an application in which users can register to play, where in each game they will have to answer several questions, from different categories, where it will be saved
A ranking with the maximum score of the user and can be compared with other users, it will also have a section that indicates their correct guess and in which category they get the most questions right.

.Technologies used to carry out:

* MongoDB: MongoDB is an open-source NoSQL database that uses a document-based data model for information storage and retrieval.
* React JS: It's a framework created by Facebook that's widely used to create user interface components. Chosen for the large volume of documentation and the fact that it is the framework used during the previous courses.
* WikiData: It's a free knowledge base modified by humans as well as machines, and it's where we'll get our questions from.
* Microsoft Azure: A cloud computing platform that provides infrastructure, platform, and software-as-a-service services to host, manage, and scale online applications and services.

=== Design
The designed website is composed of a frontend in React, a backend in Node.js and is documented using Asciidoc. Each user will have their own account where their information will be saved. Design-related decisions are detailed in point 9.

=== Security
We guarantee the safety of the user

=== Testability
Tests will be carried out for each individual part of the application, thus ensuring the correct operation of the different modules both individually and together.

=== Interface
The graphical interface will be chosen among all the members of the team, each one contributing a sketch or idea, which will be shared and it will be decided which best fits the expected performance and which elements of these sketches are most suitable.
This will take into account the usability and needs of different types of users.


