ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Deplyment View


=== Infrastructure Level 1

image::DeploymentView.svg[Deployment View]

Motivation::

This diagram shows us the process the application goes through when it is deployed.


=== Infrastructure Level 2

==== APP

"App": It is the part with which the user interacts. This part would be responsible for providing the visual interface and using the rest of the created classes.

==== LINK

"Link" is the part of the application that connects the rest of the parts. This will facilitate the use of the different parts of the application in the App section.

==== REGISTER

"Register" is the part of the application that handles user registration and login. It's very important as it's the first thing a potential user will encounter when they visit our page.

==== USER SERVICE

"User service" is the part of the application that generates the various services within the application to the user, such as a ranking, correctly answered questions, and so on.

==== QUESTION GENERATOR

"Question generator" is the part of the application that, using the data from Wikidata and some pre-created templates, generates the questions and possible answers of the application.

==== WIKIDATA

Wikidata” is the API that you will use to obtain the data for the questions. Wikidata is a free and collaborative database that can be read and edited by both humans and machines. It provides a common source of certain types of data that can be used by Wikimedia projects. 
