ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Deplyment View


=== Infrastructure Level 1

image::07-deployment.svg[Deployment View]

Motivation::

The infrastructure consists on a set of containers that will be deployed in a cloud provider. This containers will be responsible for the different parts of the application. The infrastructure will be monitored by Prometheus and Grafana. The data will be stored in a MongoDB database. The application will use Wikidata to obtain the data for the questions.

=== Infrastructure Level 2

==== Webapp

This container is responsible for the user interface.

==== Question Generator

Question generator is the part of the application that generates the questions for the users. 

==== User Service

User Service is the part of the application that handles users information.

==== Auth Service

Auth Service is the part of the application that handles the authentication of the users. It's very important as it's the first thing a potential user will encounter when they visit our page.

==== Stats Service

Stats Service is the part of the application that handles the statistics of the users. 

==== Gateway service

Gateway service is the part of the application that handles the communication between the different parts of the application. 

==== MongoDB

MongoDB is the database that will store the data of the users, the questions, the answers, and the statistics of the application.

==== Prometheus

Prometheus is the monitoring tool that will be used to monitor the application. 

==== Grafana

Grafana is the visualization tool that will be used to visualize the monitoring of the application.

==== Wikidata

WikiData is the API that you we will use to obtain the data for the questions. Wikidata is a free and collaborative database that can be read and edited by both humans and machines. It provides a common source of certain types of data that can be used by Wikimedia projects.
